version: '3.8'
services:
  upload-service:
    image: upload-service:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - SERVER_PORT=8081
      - YANDEX-CLOUD_BUCKET-NAME=${BUCKET_NAME}
      - YANDEX-CLOUD_ACCESS-KEY=${ACCESS_KEY}
      - YANDEX-CLOUD_SECRET-KEY=${SECRET_KEY}