spring:
  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 25MB
server:
  port: 8081
yandex-cloud:
  bucket-name: ${BUCKET_NAME}
  access-key: ${ACCESS_KEY}
  secret-key: ${SECRET_KEY}